import { theme, config } from "@/theme"
import { YamadaUIScripts } from "@/utils/yamada-ui-scripts"
import { UIProvider } from "@yamada-ui/react"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Next.js App - Yamada UI",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>

      <body suppressHydrationWarning>
        <YamadaUIScripts />

        <UIProvider config={config} theme={theme}>
          {children}
        </UIProvider>
      </body>
    </html>
  )
}
