import { theme, config } from "@/theme"
import {
  ColorModeScript,
  ThemeSchemeScript,
  UIProvider,
} from "@yamada-ui/react"
import type { Metadata } from "next"
import Script from "next/script"

export const metadata: Metadata = {
  title: "Next.js App - Yamada UI",
  description: "Generated by create next app",
}

const { initialThemeScheme, initialColorMode } = { ...config }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" data-mode="light">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>

      <body>
        <Script id="yamada-ui-custom">
          <ThemeSchemeScript initialThemeScheme={initialThemeScheme} />
          <ColorModeScript initialColorMode={initialColorMode} />
        </Script>
        <UIProvider config={config} theme={theme}>
          {children}
        </UIProvider>
      </body>
    </html>
  )
}
